name: URL Checks
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  get_urls:
    name: Load URLs
    runs-on: ubuntu-latest
    outputs: 
      matrix: ${{ steps.load_urls.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - name: get specified property
        id: load_urls
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "src/data/links.json"
          prop_path: "linkData.items.url"
          
  check:
    name: Check URLs
    runs-on: ubuntu-latest
    needs: [get_urls]
    strategy:
      matrix:
        value: ${{ needs.get_urls.outputs.matrix }}
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: ${{matrix.value}}
          follow-redirect: true
