name: URL Checks
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  get_urls:
    name: Load URLs
    runs-on: ubuntu-latest
    outputs: 
      matrix: ${{ steps.get_urls.outputs.urls }}
    steps:
      - id: read_json
        run: |
          content=`cat ./src/data/links.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"
      - id: get_urls
        run: |
          urls=fromJson(steps.read_json.outputs.packageJson).linkData
          echo '::set-output \"urls::$urls\"'

  check:
    name: Check URLs
    runs-on: ubuntu-latest
    needs: [get_urls]
    strategy:
      matrix:
        value: ${{ needs.get_urls.outputs.matrix }}
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: ${{matrix.value}}
          follow-redirect: true
