name: URL Checks
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  get_urls:
    name: Load URLs
    runs-on: ubuntu-latest
    outputs: 
      matrix: ${{ steps.get_urls.outputs.LINK_DATA }}
    steps:
      - uses: actions/checkout@v3
      - id: read_json
        run: |
          content=`cat ./src/data/links.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          json=${{fromJSON($content)}}
          linkData=json.linkData
          echo "LINK_DATA=linkData" >> $GITHUB_OUTPUT

  check:
    name: Check URLs
    runs-on: ubuntu-latest
    needs: [get_urls]
    strategy:
      matrix:
        value: ${{ needs.get_urls.outputs.matrix }}
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: ${{matrix.value}}
          follow-redirect: true
